### ISSUE TITLE
Unable to upload a video

### ISSUE THREAD

**Issue by sportool** [mad-lab-fau/mad-gui#15]
**Describe the bug**
The software does not allow to upload a video following the selection of a dataset. 

**To Reproduce**
1. Go to load data
2. Click on select data and select the .csv file
3. Click on select video and select the mp4 file
4. Click on start processing

**Expected behavior**
The software should load data and video

**Screenshots**
The software allows to select only csv files when selecting a video.

<img width="678" alt="Screenshot (19)" src="https://user-images.githubusercontent.com/109573090/215265535-ab71be42-6a2c-492a-bee5-23d9e7f4ecbe.png">

**Desktop (please complete the following information):**
 - Windows 11 pro
 - 10.0.22000

**Comment by MalteOlle** [comment]
Thanks for the detailed information! Indeed, you have to create your own importer. Simply inherit from `mad_gui.plugins.BaseImporter` and make sure to set the property for the file types (see https://github.com/mad-lab-fau/mad-gui/blob/main/mad_gui/plugins/base.py#L43).

Also, you may want to take a look at [this general information about plugins in the MaD GUI](https://github.com/mad-lab-fau/mad-gui/blob/main/mad_gui/plugins/base.py#L43) as well as this [more detailed explanation](https://mad-gui.readthedocs.io/en/latest/plugin_importer.html#overview) regarding how to develop your own plugin (importer).

I think this should solve the issue. If so, please close the issue, otherwise please leave another comment :-)

**Comment by sportool** [comment]
Thanks for the reply! I don't quite know hot to use python (I was hoping for a faster solution) but I'll give it a try.

**Comment by MalteOlle** [comment]
Ok, then it may be tricky. However, the "standalone" exe-file we provided is just an example, and you (or someone you collaborate with) would have to create a version for your needs anyway, e.g. for the annotations you want to make. Unfortunately, I cannot provide more help with the general python setup, but you'll find some hints here: https://mad-gui.readthedocs.io/en/latest/preparation.html

- see 1.3.1 Installation for Development
- use `pip install mad_gui`
- then continue with 1.4 and 1.5
